export default postTypes = {

  GET_POSTS: "GET_POSTS",
  GET_POSTS_REQUESTED: "GET_POSTS_REQUESTED",
  GET_POST_BY_USER_ID: "GET_POST_BY_USER_ID",
  GET_POST_BY_USER_ID_REQUESTED: "GET_POST_BY_USER_ID_REQUESTED",
  NEW_POST_REQUESTED: "NEW_POST_REQUESTED",
  UPDATE_POST_REQUESTED: "UPDATE_POST_REQUESTED",

}